### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by fulup-bzh** [jeremiedmns/ha-teleinfo#1]
Bonjours, j'ai installé le 'teleinfo' à la mano ou via le store sans plus de succès.

Avec minicom, je vois:
* que mon compteur retourne bien les info sur /dev/ttyAMA0
* via le log que le composant est bien loader dans home assistant

Si je place la config dans configuration.yaml home assistant ne redémarre par proprement mais rien dans les log. En fait sur mon dashboard ca plante sur la partie "Energy" et du coup les autre tab Map","logbook", ... ne sont pas visible.

C'est comme sur la config plantais eu moment de l'initialisation du composant, mais je ne vois rien dans les log, je suis donc un peu aveugle.

Une idée ?

**Comment by fulup-bzh** [comment]
Install sur derniere version sans plus de succès
```
 File "<template>", line 1, in top-level template code
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 1702, in forgiving_int_filter
    raise_no_default("int", value)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 1394, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'None' when rendering template '{{ state_attr('sensor.teleinfo', 'ISOUSC') | int }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 536, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 422, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'None' when rendering template '{{ state_attr('sensor.teleinfo', 'ISOUSC') | int }}' but no default was specified
2022-10-21 13:31:30.160 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: int got invalid input 'None' when rendering template '{{ state_attr('sensor.teleinfo', 'ISOUSC') | int }}' but no default was specified') while processing template 'Template("{{ state_attr('sensor.teleinfo', 'ISOUSC') | int }}")' for attribute '_attr_native_value' in entity 'sensor.teleinfo_intensite_souscrite'
2022-10-21 13:31:30.173 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ state_attr('sensor.teleinfo', 'IINST') | int }}")
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 420, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/template.py", line 1915, in _render_with_context
    return template.render(**kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render

```
